### ISSUE TITLE
An error about krigeST()

### ISSUE THREAD

**Issue by sue-shine** [rsbivand/upna18#1] opened 2020-07-01 11:56 UTC
Excuse me, sorry to bother you. I have met a question when coding.as the code follows:
>spat_pred_grid1 <- expand.grid(
  lon = seq(117, 118, length = 20),
  lat = seq(30, 31, length = 20)) %>%
  SpatialPoints(proj4string = CRS(proj4string(STOBJ1))) 
>gridded(spat_pred_grid1) <- TRUE 
>temp_pred_grid1 <- as.Date("1991-06-01") + seq(3, 23, length = 6)
>DE_pred1 <- STF(sp = spat_pred_grid1, 
               time = temp_pred_grid1) 
>STOBJ1 <- as(STOBJ1[,"1991-06-01::1991-06-25"], "STIDF")
>pred_kriged <- krigeST(p ~ 1, 
                       data = STOBJ1, 
                       newdata = DE_pred1,
                       modelList = sepVgm, 
                       computeVar = TRUE)
 but a error coming
##Error in chol.default(A) : the leading minor of order 88 is not positive definite

**Comment by rsbivand** [comment] 2020-07-01 13:29
Could you please provide a reproducible example? This is a **gstat** question, really. With a reproducible example, try here if you like, but better to post on R-sig-geo.

**Comment by sue-shine** [comment] 2020-07-01 14:19
[data.xlsx](https://github.com/rsbivand/upna18/files/4858323/data.xlsx)
[location.xlsx](https://github.com/rsbivand/upna18/files/4858336/location.xlsx)
[date.xlsx](https://github.com/rsbivand/upna18/files/4858337/date.xlsx)

I'sorry that I don't know how to put on R-sig-geo,here gives my data and code.
Please confirm whether the attachment can be opened.
Thank you for you time!
 <loc<-read.csv("F:/1Guichi1991-2015/schdata.SU/location.csv")
<date<-read.csv("F:/1Guichi1991-2015/schdata.SU/date.csv")
<data<-read.csv("F:/1Guichi1991-2015/schdata.SU/data.csv")

<library("dplyr")
<library("tidyr")
<library("STRbook")
<library("sp")
<library("spacetime")

#STFDF
<spat_part <- SpatialPoints(coords = loc[,c("lon", "lat")]) 

<date$time<-as.character(date$time)  
<temp_part<-date$time    
<temp_part <- as.Date(temp_part)
<class(date$time)

<data$VillageID<-as.integer(data$VillageID)
<all(unique(data$VillageID) == loc$VillageID) 
<STOBJ1<- STFDF(sp = spat_part,
               time = temp_part, 
               data = data)

<proj4string(STOBJ1) <- CRS("+proj=longlat +ellps=WGS84") 
<library(gstat)
<vv<-variogram(object=p~1,  
              data=STOBJ1,
              width=2,   
              cutoff=28,
              tlags=0.01:6.1,tunit="days")

<plot(vv)
#separable model
<sepVgm <- vgmST(stModel = "separable",     
                space = vgm(10, "Exp", 400, nugget = 0.1), 
                time = vgm(10, "Exp", 1, nugget = 0.1), 
                sill = 20)   
<sepVgm <- fit.StVariogram(vv, sepVgm)

<spat_pred_grid<- expand.grid(
< lon = seq(117, 118, length = 20),
< lat = seq(30, 31, length = 20)) %>%
< SpatialPoints(proj4string = CRS(proj4string(STOBJ1)))
<gridded(spat_pred_grid) <- TRUE 

<temp_pred_grid <- as.Date("1991-06-01") + seq(1, 6, length = 6)


<DE_pred<- STF(sp = spat_pred_grid, 
                time = temp_pred_grid) 

<STOBJ1 <- as(STOBJ1[,"1991-06-01::1991-06-06"], "STIDF")

<STOBJ1 <- subset(STOBJ1, !is.na(STOBJ1$p))

<pred_kriged <- krigeST(p ~ 1,
                       data = STOBJ1,
                       newdata = DE_pred, # prediction grid
                       modelList = sepVgm, # semivariogram
                       computeVar = TRUE)

**Comment by rsbivand** [comment] 2020-07-01 14:29
No, these are your data, which I will not use. Subscribe to R-sig-geo, and provide a reproducible example with built-in code. Also provide an affiliation, this looks like homework.

**Comment by sue-shine** [comment] 2020-07-01 15:34
Here is the reproducible example, but while I was working with my own data, the  error occurred. Fudan University in China.
library("sp")
library("spacetime")
library("ggplot2")
library("dplyr")
library("gstat")
library("RColorBrewer")
library("STRbook")
library("tidyr")

<data("STObj3", package = "STRbook") 
<STObj4 <- STObj3[,"1993-07-01::1993-07-31"]
<library(gstat)
<vv<-variogram(object=z~1+lat, t
              data=STObj3,
              width=80,
              cutoff=1000,
              tlags=0.01:6.01)        #0 days to 6 days
<plot(vv)


<sepVgm <- vgmST(stModel = "separable",     
                space = vgm(10, "Exp", 400, nugget = 0.1),
                        
                time = vgm(10, "Exp", 1, nugget = 0.1), 
                sill = 20)  
<sepVgm <- fit.StVariogram(vv, sepVgm)

<spat_pred_grid <- expand.grid(
< lon = seq(-100, -80, length = 20),
<lat = seq(32, 46, length = 20)) %>%
<SpatialPoints(proj4string = CRS(proj4string(STObj3))) 
<gridded(spat_pred_grid) <- TRUE 

<temp_pred_grid <- as.Date("1993-07-01") + seq(3, 28, length = 6)

<DE_pred <- STF(sp = spat_pred_grid, 
               time = temp_pred_grid) 

<STObj5 <- as(STObj4[, -14], "STIDF") # convert to STIDF
<STObj5 <- subset(STObj5, !is.na(STObj5$z))

<pred_kriged <- krigeST(z ~ 1 + lat, # latitude trend
                       data = STObj5, # data set w/o 14 July
                       newdata = DE_pred, # prediction grid
                       modelList = sepVgm, # semivariogram
                       computeVar = TRUE)

**Comment by rsbivand** [comment] 2020-07-02 10:33
This question has nothing to do with this repository. If you feel like it, post an issue on: https://github.com/andrewzm/STRbook, or post a reproducible example on R-sig-geo after subscribing. Closing as irrelevant.

**Closed as completed by rsbivand** 2020-07-02 10:33 UTC
